import { useMemo, useState } from 'react';
import Prism from 'prismjs';
import 'prismjs/components/prism-markup.js';
import 'prismjs/components/prism-css.js';
import 'prismjs/components/prism-javascript.js';
import 'prismjs/components/prism-jsx.js';
import 'prismjs/components/prism-typescript.js';
import 'prismjs/components/prism-json.js';
import 'prismjs/components/prism-python.js';
import './codex-artifact-panel.css';

const aliases={markup:'markup',html:'markup',css:'css',javascript:'javascript',jsx:'jsx',typescript:'typescript',tsx:'tsx',json:'json',python:'python'};
function escape(value){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function highlight(code,language){const grammar=Prism.languages[aliases[language]||language];if(!grammar)return escape(code);try{return Prism.highlight(code,grammar,aliases[language]||language)}catch{return escape(code)}}
function preview(artifacts){const html=artifacts.find(a=>a.language==='markup'||/\.html?$/i.test(a.filename));if(!html)return '';const css=artifacts.filter(a=>a.language==='css'||/\.css$/i.test(a.filename)).map(a=>a.code).join('\n');const js=artifacts.filter(a=>['javascript','jsx','typescript','tsx'].includes(a.language)||/\.(js|jsx|ts|tsx)$/i.test(a.filename)).map(a=>a.code).join('\n');let d=html.code;if(!/<html/i.test(d))d=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body>${d}</body></html>`;if(css)d=d.replace(/<\/head>/i,`<style>${css.replace(/<\/style/gi,'<\\/style')}</style></head>`);if(js)d=d.replace(/<\/body>/i,`<script>${js.replace(/<\/script/gi,'<\\/script')}</script></body>`);return d}
function download(name,body,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),800)}
export default function CodexArtifactPanel({open,artifacts,activeId,onSelect,onClose,onUpdateArtifact,onBuildExe}){const active=artifacts.find(a=>a.id===activeId)||artifacts[0];const [view,setView]=useState('code');const [copied,setCopied]=useState(false);const documentText=useMemo(()=>preview(artifacts),[artifacts]);if(!open||!active)return null;const lines=String(active.code||'').split('\n');const copy=async()=>{try{await navigator.clipboard?.writeText(active.code);setCopied(true);setTimeout(()=>setCopied(false),1200)}catch{}};return <aside className="codex-artifact-panel"><header><div><span>CODEX · ARQUIVOS</span><strong>Arquivos do projeto</strong></div><button onClick={onClose}>Fechar</button></header><nav className="codex-artifact-files">{artifacts.map(a=><button key={a.id} className={a.id===active.id?'active':''} onClick={()=>onSelect(a.id)}>{a.filename}<small>{a.languageLabel||a.language}</small></button>)}</nav><div className="codex-artifact-tabs"><button className={view==='code'?'active':''} onClick={()=>setView('code')}>Código</button><button className={view==='preview'?'active':''} disabled={!documentText} onClick={()=>documentText&&setView('preview')}>Preview</button></div>{view==='code'?<><div className="codex-artifact-toolbar"><input value={active.filename} onChange={e=>onUpdateArtifact(active.id,{filename:e.target.value})}/><div><button onClick={copy}>{copied?'Copiado':'Copiar'}</button><button onClick={()=>download(active.filename,active.code)}>Baixar</button>{onBuildExe&&<button className="build" onClick={onBuildExe}>Compilar .exe</button>}</div></div><div className="codex-artifact-editor"><div className="codex-artifact-gutter">{lines.map((_,i)=><span key={i}>{i+1}</span>)}</div><pre><code dangerouslySetInnerHTML={{__html:highlight(active.code,active.language)}}/></pre></div></>:<div className="codex-artifact-preview"><iframe title="Preview do projeto" srcDoc={documentText} sandbox="allow-scripts"/></div>}</aside>}
