export const infoItems = [
  { id:'vibe-coding', n:'01', title:'Vibe Coding & IDE integrada', summary:'Visualização do projeto, árvore de arquivos e diffs de código enquanto a tarefa acontece.', body:'O Vibe Coding é o ambiente de desenvolvimento integrado da Prism IA: enquanto a IA gera ou modifica seu projeto, você acompanha tudo em tempo real, sem esperar o resultado final para entender o que está sendo feito. A árvore de arquivos mostra a estrutura completa do projeto sendo construído, permitindo navegar entre pastas e arquivos conforme eles são criados. Já o comparador de diffs destaca exatamente o que foi adicionado, removido ou alterado em cada trecho de código, facilitando revisar mudanças sem precisar reler o arquivo inteiro. Quando uma resposta envolve mais de dois arquivos, esse painel abre automaticamente.' },
  { id:'codex', n:'02', title:'Prism Codex', summary:'Chat completo com métricas de sessões, mensagens, tokens, dias ativos, streaks e atividade.', body:'O Prism Codex é a experiência mais completa da plataforma: uma interface de chat funcional combinada com um painel de métricas pessoais sobre o seu uso. Nele você acompanha, em tempo real, o número de sessões abertas, o total de mensagens trocadas, o consumo de tokens, quantos dias você usou a plataforma (dias ativos), sua sequência de uso contínuo (streak) e um heatmap no estilo GitHub que mostra visualmente sua atividade ao longo do tempo. É também no Codex que o mascote da Prism aparece, reagindo às suas interações e métricas.' },
  { id:'home', n:'03', title:'Prism Home', summary:'Uma experiência direta, focada em código, para quem quer chegar da ideia à execução sem excesso de interface.', body:'O Prism Home é a versão enxuta da plataforma: uma interface sóbria e minimalista, sem dashboard de métricas e sem mascote, pensada para quem só quer escrever um prompt e receber código, sem elementos visuais adicionais no caminho. Mesmo assim, mantém os recursos essenciais — histórico de conversas, seleção de modelo e o Effort Slider — em uma barra lateral retrátil, mantendo o foco total na tarefa técnica.' },
  { id:'effort', n:'04', title:'Effort Slider', summary:'Controle do esforço computacional aplicado à tarefa, do padrão ao máximo desempenho.', body:'O Effort Slider permite ajustar, para qualquer modelo escolhido, o quanto de poder de processamento será dedicado à sua solicitação. No nível padrão, a resposta prioriza agilidade. Ao aumentar o esforço, a Prism IA passa a acionar mais motores em paralelo e aplicar mais camadas de verificação, até chegar ao nível máximo — o modo Ultracode. Esse controle dá liberdade para equilibrar velocidade e profundidade conforme a complexidade real da tarefa, sem precisar trocar de modelo.' },
  { id:'ultracode', n:'05', title:'Modo Ultracode', summary:'Execução simultânea de três motores para projetos exigentes, seguida de síntese dos resultados.', body:'O Ultracode é o nível mais avançado de processamento da Prism IA. Nele, sua solicitação é enviada ao mesmo tempo para os três motores disponíveis na plataforma, cada um contribuindo com sua especialidade — raciocínio e arquitetura, geração de código e validação/otimização. Em seguida, um módulo interno compara as três respostas, resolve inconsistências entre elas e entrega um resultado final consolidado. É o modo recomendado para projetos grandes, críticos ou que exigem o maior nível de confiabilidade possível, com contrapartida de maior tempo de resposta e consumo de créditos.' },
];
export const modelItems = [
  { id:'nano', n:'01', name:'Prism Nano 1.0A', level:'LEVE', summary:'Respostas rápidas, dúvidas pontuais e trechos simples de código. Prioriza velocidade sobre profundidade.', body:'O Nano é o modelo de entrada da Prism IA, pensado para interações curtas e objetivas. Ideal quando você precisa de uma resposta imediata — como tirar uma dúvida rápida de sintaxe ou gerar um pequeno trecho de código — sem necessidade de raciocínio elaborado ou múltiplas etapas de verificação.' },
  { id:'mini', n:'02', name:'Prism Mini 1.0A', level:'RÁPIDO', summary:'Mais capacidade de manter contexto em tarefas curtas. Ideal para prototipagem rápida.', body:'O Mini expande a capacidade do Nano ao manter o contexto da conversa por mais tempo, permitindo tarefas com algumas etapas conectadas entre si. É uma boa escolha para prototipar ideias rapidamente, testar abordagens e iterar sobre pequenas funcionalidades sem grande complexidade.' },
  { id:'edge', n:'03', name:'Prism Edge 1.0A', level:'EQUILIBRADO', summary:'Combina velocidade e raciocínio para tarefas de programação que exigem mais de uma etapa.', body:'O Edge equilibra agilidade e profundidade de raciocínio, sendo indicado para tarefas de programação do dia a dia que envolvem múltiplas etapas — como implementar uma funcionalidade que depende de outras partes do código já existentes, ou resolver um bug que exige investigação antes da correção.' },
  { id:'tex', n:'04', name:'Prism Tex 1.0A', level:'TÉCNICO', summary:'Focado em geração e revisão de texto técnico, documentação e explicações longas de arquitetura.', body:'O Tex é voltado para quem precisa de conteúdo técnico bem estruturado além do código em si — documentação de projetos, explicações detalhadas de decisões de arquitetura, comentários extensos ou materiais de referência para times de desenvolvimento.' },
  { id:'taff', n:'05', name:'Prism Taff 2.0', level:'FLAGSHIP', summary:'O modelo principal. Combina raciocínio, geração de código e validação em paralelo para tarefas complexas.', body:'O Taff 2.0 é o modelo mais completo da Prism IA, projetado para projetos complexos que exigem qualidade em todas as frentes: planejamento de arquitetura bem fundamentado, código gerado com precisão e validação técnica antes da entrega final. É o modelo recomendado quando o resultado precisa estar pronto para produção.' },
];
