import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../lib/auth.jsx';
import { modelItems } from '../content/prismTexts.js';
import PrismIcon from '../components/PrismIcon.jsx';

const MODELS=[['prism-nano-1.0','Prism Nano 1.0A','Rápido','Tarefas curtas e respostas diretas',0],['prism-mini-1.0','Prism Mini 1.0A','Equilibrado','Contexto e prototipagem rápida',0],['prism-edge-1.0','Prism Edge 1.0A','Avançado','Programação com múltiplas etapas',2],['prism-tex-1.5','Prism Tex 1.5A','Técnico','Documentação e trabalho técnico',2],['prism-taff-1.0','Prism Taff 1.0A','Pro','Engenharia e problemas complexos',3],['prism-taff-2.0','Prism Taff 2.0','Flagship','Projetos grandes e execução ponta a ponta',3]];
const PLANS={'Grátis':0,free:0,Base:1,base:1,Medium:2,medium:2,Pro:3,pro:3,Empresarial:4,enterprise:4};

export default function ModelsV2(){const {user}=useAuth();const navigate=useNavigate();const entitlement=PLANS[user?.plan]??0;return <div className="prism-library-page"><header className="prism-library-topbar"><Link className="prism-library-brand" to="/chat"><img src="/prism-logo.svg" alt=""/>Prism IA</Link><nav className="prism-library-nav"><Link to="/informacoes">Informações</Link><Link className="active" to="/modelos">Modelos</Link><Link to="/termos">Termos</Link><Link to="/chat">Chat</Link><Link to="/codex">Codex</Link></nav><Link className="prism-library-account" to="/configuracoes"><span className="avatar">{String(user?.name||'P').slice(0,1).toUpperCase()}</span>{user?.name||'Conta'}</Link></header><main className="prism-library-main"><section className="prism-library-hero"><div className="prism-library-eyebrow">Modelos / Prism IA</div><h1>Escolha o motor.<br/><em>Continue trabalhando.</em></h1><p>Cada modelo mantém a mesma interface, ferramentas e projetos. O que muda é a capacidade, o custo de execução e a profundidade adequada para a tarefa.</p></section><div className="prism-library-card-grid">{MODELS.map(([id,name,tier,summary,required])=><article className="prism-library-card" key={id}><div><div className="card-top"><span className="glyph"><PrismIcon name="model" size={14}/></span><span className="rank">{tier}</span></div><h3>{name}</h3><p>{summary}</p>{entitlement<required&&<div className="locked">Disponível em um plano superior</div>}</div><div className="card-actions"><button className="prism-library-button primary" disabled={entitlement<required} onClick={()=>{if(entitlement<required)return;localStorage.setItem('prism.home.model',id);navigate('/chat');}}><PrismIcon name="send" size={12}/>{entitlement<required?'Bloqueado':'Usar no Chat'}</button><Link className="prism-library-button" to={id==='prism-taff-2.0'?'/prism-taff':`/modelos/${id.replace('prism-','')}`}><PrismIcon name="layers" size={12}/>Detalhes</Link></div></article>)}</div><section className="prism-library-compare"><h2>Como a linha se distribui</h2><table className="prism-library-table"><thead><tr><th>Modelo</th><th>Foco</th><th>Velocidade</th><th>Profundidade</th></tr></thead><tbody>{modelItems.map((item)=>{const map=MODELS.find((m)=>m[1]===item.name)||[];return <tr key={item.id}><td>{item.name}</td><td>{item.summary.split('.')[0]}.</td><td>{map[2]||item.level}</td><td>{map[4]>=3?'Alta':map[4]>=2?'Média-alta':'Direta'}</td></tr>})}</tbody></table></section></main></div>}
