import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api } from '../lib/api.js';
import { useAuth } from '../lib/auth.jsx';
import PrismIcon from '../components/PrismIcon.jsx';

const read=(key,fallback='')=>{try{return localStorage.getItem(key)||fallback;}catch{return fallback;}};
function number(value){return new Intl.NumberFormat('pt-BR').format(Math.max(0,Number(value||0)));}
function date(value){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d);}

export default function SettingsV2(){const{user,logout}=useAuth();const navigate=useNavigate();const[usage,setUsage]=useState(null);const[billing,setBilling]=useState(null);const[health,setHealth]=useState(null);const[effort,setEffort]=useState(()=>read('prism-default-effort','medium'));const[compact,setCompact]=useState(()=>read('prism-compact-sidebar')==='true');const[instructions,setInstructions]=useState(()=>read('prism-custom-instructions'));const[memory,setMemory]=useState(()=>read('prism-memory-enabled','true')!=='false');const[instructionsState,setInstructionsState]=useState('idle');
useEffect(()=>{Promise.all([api.get('/chat/usage'),api.get('/billing/status'),api.get('/health'),api.get('/user/me')]).then(([u,b,h,account])=>{setUsage(u);setBilling(b);setHealth(h);if(typeof account?.user?.assistant_instructions==='string'){setInstructions(account.user.assistant_instructions);localStorage.setItem('prism-custom-instructions',account.user.assistant_instructions);}}).catch(()=>{});},[]);
function save(key,value){localStorage.setItem(key,value);}
async function saveInstructions(){setInstructionsState('saving');try{const result=await api.patch('/user/me',{assistant_instructions:instructions});setInstructions(result?.user?.assistant_instructions||instructions);save('prism-custom-instructions',result?.user?.assistant_instructions||instructions);setInstructionsState('saved');window.setTimeout(()=>setInstructionsState('idle'),1400);}catch{setInstructionsState('error');}}
function signOut(){logout();navigate('/login',{replace:true});}
return <div className="prism-settings-page"><header className="prism-settings-top"><Link className="prism-library-brand" to="/chat"><img src="/prism-logo.svg" alt=""/>Prism IA</Link><Link to="/chat">Voltar ao Chat</Link></header><main className="prism-settings-main"><div className="prism-settings-heading"><div><h1>Configurações</h1><p>Preferências do seu espaço de trabalho e conta.</p></div><div className="prism-library-actions"><Link className="prism-library-button" to="/modelos"><PrismIcon name="model" size={12}/>Modelos</Link><Link className="prism-library-button" to="/codex"><PrismIcon name="code" size={12}/>Codex</Link></div></div><div className="prism-settings-grid">
<section className="prism-settings-card full"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><div><h2>Instruções do Prism</h2><p>Regras que acompanham suas próximas execuções em qualquer IA configurada.</p></div><button className="prism-library-button primary" onClick={saveInstructions} disabled={instructionsState==='saving'}>{instructionsState==='saving'?'Salvando…':instructionsState==='saved'?'Salvo':'Salvar'}</button></div><textarea className="prism-setting-input" style={{width:'100%',height:120,padding:'9px',resize:'vertical'}} value={instructions} onChange={(e)=>{setInstructions(e.target.value);save('prism-custom-instructions',e.target.value)}} placeholder="Ex.: escreva em português, seja direto e valide o código antes de responder." />{instructionsState==='error'&&<small style={{display:'block',marginTop:6,color:'#a04c47'}}>Não foi possível salvar no servidor.</small>}</section>
<section className="prism-settings-card"><h2>Preferências</h2><p>Controle como novas tarefas começam.</p><div className="prism-setting-row"><div><strong>Esforço padrão</strong><small>Profundidade inicial das novas execuções.</small></div><select className="prism-setting-select" value={effort} onChange={(e)=>{setEffort(e.target.value);save('prism-default-effort',e.target.value)}}><option value="low">Baixo</option><option value="medium">Médio</option><option value="high">Alto</option><option value="max">Máximo</option><option value="ultracode">Ultracode</option></select></div><div className="prism-setting-row"><div><strong>Sidebar compacta</strong><small>Usa menos espaço lateral nas superfícies compatíveis.</small></div><button className="prism-library-button" onClick={()=>{const next=!compact;setCompact(next);save('prism-compact-sidebar',String(next));}}>{compact?'Ativa':'Inativa'}</button></div><div className="prism-setting-row"><div><strong>Memória local</strong><small>Preserva preferências simples deste navegador.</small></div><button className="prism-library-button" onClick={()=>{const next=!memory;setMemory(next);save('prism-memory-enabled',String(next));}}>{memory?'Ativa':'Inativa'}</button></div></section>
<section className="prism-settings-card"><h2>Conta</h2><p>Identidade e estado do serviço conectado.</p><div className="prism-setting-row"><div><strong>{user?.name||'Usuário'}</strong><small>{user?.email||'Sem email'}</small></div><span className="prism-setting-pill">{user?.plan||'Grátis'}</span></div><div className="prism-setting-row"><div><strong>Backend</strong><small>Banco, autenticação e execução.</small></div><span className="prism-setting-pill">{health?.ok?'Conectado':'Indisponível'}</span></div><div className="prism-setting-row"><div><strong>Modelos</strong><small>Provedores que podem atender suas tarefas.</small></div><span className="prism-setting-pill">{health?.ai?'Configurados':'Sem chave'}</span></div></section>
<section className="prism-settings-card full"><h2>Uso</h2><p>Consumo desta conta segundo o backend da Prism IA.</p><div className="prism-setting-metric"><div><strong>{number(usage?.daily?.used)}</strong><span>uso diário / {number(usage?.daily?.limit)}</span></div><div><strong>{number(usage?.weekly?.used)}</strong><span>uso semanal / {number(usage?.weekly?.limit)}</span></div><div><strong>{date(usage?.weekly?.resetsAt)}</strong><span>próxima renovação</span></div></div></section>
<section className="prism-settings-card"><h2>Cobrança</h2><p>Estado da integração de pagamento.</p><div className="prism-setting-row"><div><strong>Stripe</strong><small>{billing?.enabled?'Checkout disponível.':'Nenhuma cobrança real está conectada.'}</small></div><span className="prism-setting-pill">{billing?.enabled?'Ativo':'Simulação'}</span></div></section>
<section className="prism-settings-card prism-setting-danger"><h2>Sessão</h2><p>Sair encerra o acesso local à sua conta.</p><button onClick={signOut} className="prism-library-button"><PrismIcon name="settings" size={12}/>Sair da Prism IA</button></section>
</div></main></div>}
