import { Link, useParams } from 'react-router-dom';
import PrismIcon from '../components/PrismIcon.jsx';
const TOPICS={
roteamento:['Roteamento','Como a Prism escolhe provedores e modos.',['A Prism separa a escolha do modelo lógico da execução concreta. O modelo pedido determina requisitos de plano e perfil; o roteador então usa os provedores configurados, tempo de resposta e disponibilidade para concluir a tarefa.','Quando ferramentas reais estão disponíveis, busca, MCP, Skills e runtime entram no mesmo ciclo de execução em vez de ficarem escondidos atrás de uma resposta textual.']],
motores:['Motores externos','Os provedores que podem atender uma tarefa.',['A plataforma pode operar com múltiplos provedores. A mesma experiência do Prism mantém modelos Prism no produto enquanto o backend distribui a execução entre provedores configurados.','O usuário não precisa reescrever o pedido para cada motor. O orquestrador normaliza ferramentas, esforço e resultados antes de devolver a resposta.']],
openrouter:['OpenRouter','Uma camada de acesso a modelos compatíveis.',['Quando configurado, OpenRouter pode atuar como provedor intermediário para modelos compatíveis com a API OpenAI. Sua presença não substitui os outros provedores: ele é mais uma rota disponível no fallback.']],
orquestracao:['Orquestração','Ferramentas, fallback e síntese.',['A execução moderna da Prism é agentic: o modelo pode chamar ferramentas, observar o resultado e continuar por novas etapas.','A plataforma registra eventos de execução para tornar visível o que está acontecendo: conexão de MCP, provider rounds, ferramentas, comandos, artefatos e finalização.']],
creditos:['Créditos e tokens','Como o uso é registrado.',['Cada execução reserva uso antes de chamar o provedor. Ao terminar, os tokens retornados são registrados e a reserva é consolidada. Se a execução falhar, a reserva é liberada.']],
privacidade:['Privacidade','Isolamento de conta e projeto.',['Sessões, mensagens, uploads, projetos e integrações são ligados ao usuário autenticado. O runtime só abre um workspace de projeto depois de validar projectId e userId juntos.','Comandos são executados dentro do workspace e passam por uma política de executáveis e caminhos antes de serem iniciados.']],
limites:['Limites','Rate limiting, planos e segurança.',['A API aplica limite por IP e as rotas de chat validam modelo, esforço e plano antes da execução. O runtime também restringe comandos e caminhos perigosos no modo seguro.']]
};
export default function TermDetailV2(){const{topic}=useParams();const data=TOPICS[topic]||TOPICS.roteamento;return <div className="prism-detail-page"><header className="prism-library-topbar"><Link className="prism-library-brand" to="/chat"><img src="/prism-logo.svg" alt=""/>Prism IA</Link><nav className="prism-library-nav"><Link to="/informacoes">Informações</Link><Link to="/modelos">Modelos</Link><Link className="active" to="/termos">Termos</Link><Link to="/chat">Chat</Link><Link to="/codex">Codex</Link></nav></header><main className="prism-detail-main"><Link className="prism-detail-back" to="/termos"><PrismIcon name="layers" size={12}/> voltar à documentação</Link><div className="prism-detail-index">PRISM / TERMOS / {topic}</div><h1>{data[0]}</h1><p className="prism-detail-summary">{data[1]}</p><div className="prism-detail-rule"/><div className="prism-detail-copy">{data[2].map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div><Link className="prism-detail-next" to="/termos">Ver todos os termos →</Link></main></div>}
