import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { api } from '../lib/api.js';
import PrismCodexIntro from '../components/PrismCodexIntro.jsx';
import './codex-rebuilt.css';

const MODELS = [
  ['prism-nano-1.0', 'Prism Nano 1.0'],
  ['prism-mini-1.0', 'Prism Mini 1.0'],
  ['prism-tex-1.5', 'Prism Tex 1.5'],
  ['prism-taff-1.0', 'Prism Taff 1.0'],
  ['prism-taff-2.0', 'Prism Taff 2.0'],
];
const PHASES = [['received','Pedido recebido'],['analyzing','Analisando o projeto'],['planning','Planejando'],['writing','Escrevendo arquivos'],['reviewing','Revisando'],['updating','Atualizando o workspace'],['completed','Concluído']];
const PLAN_DATA = [
  ['Grátis','R$0','Mini/Nano HIGH · Edge MEDIUM','5 créditos/dia · máximo 30'],
  ['Base','R$8','Mini/Nano/Edge X-HIGH','30 créditos/dia · máximo 120'],
  ['Medium','R$30','Mini/Nano/Edge MAX · Tex MEDIUM','700 créditos/dia · máximo 1000'],
  ['Pro','R$90','Mini/Nano/Edge MAX · Tex/Taff HIGH','2000 créditos/dia · máximo 3000'],
  ['Empresarial','R$140','Todos MAX · Edge EXTRA MAX','6000 créditos/dia · máximo 9000 · 30 subcontas'],
];
const VIBE_PATTERN = /\b(site|website|webapp|web app|jogo|game|app|aplicativo|api|sistema|script|scripts|c[oó]digo|code|componente|p[aá]gina|landing|projeto|arquivo|arquivos|download|baixar|npm|react|three\.js|python|godot|unity|html|css|javascript|criar|construir|implementar|programar)\b/i;
const STARTER = [
  { path:'src/App.jsx', kind:'file', content:'export default function App() {\n  return <main>Comece a construir.</main>;\n}\n' },
  { path:'src/index.css', kind:'file', content:'' },
  { path:'package.json', kind:'file', content:'{"name":"prism-project"}\n' },
];
function language(path=''){const ext=path.split('.').pop()?.toLowerCase();return ({js:'JavaScript',jsx:'JSX',ts:'TypeScript',tsx:'TSX',css:'CSS',html:'HTML',json:'JSON',py:'Python',md:'Markdown'})[ext]||'Text';}
function previewFor(files){const real=files.filter(f=>f.kind!=='folder');const html=real.find(f=>(/(^|\/)index\.html$/i).test(f.path))||real.find(f=>/\.html$/i.test(f.path));const css=real.filter(f=>/\.css$/i.test(f.path)).map(f=>f.content||'').join('\n');if(html){let out=html.content||'';if(css&&!/<style/i.test(out))out=out.replace('</head>',`<style>${css}</style></head>`);return out;}const jsx=real.find(f=>/\.(jsx|tsx)$/i.test(f.path));if(!jsx)return '';const safe=(jsx.content||'').replace(/import[\s\S]*?;\s*/g,'').replace(/export default /g,'').replace(/<\/script/gi,'<\\/script');return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script><script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script><script src="https://unpkg.com/@babel/standalone/babel.min.js"></script><style>${css}</style></head><body><div id="root"></div><script type="text/babel">${safe}\nReactDOM.createRoot(document.getElementById('root')).render(typeof App !== 'undefined' ? React.createElement(App) : React.createElement('div',null,'Preview indisponível'));</script></body></html>`;}
function StepList({phase,steps}){const active=PHASES.findIndex(([id])=>id===phase);return <div className="pcx-steps">{PHASES.map(([id,label],index)=>{const event=steps.find(x=>x.phase===id);return <div className={`pcx-step ${index<active?'done':''} ${id===phase?'active':''}`} key={id}><span className="pcx-step-mark">{index<active?'✓':id===phase?'·':''}</span><div><strong>{label}</strong>{event?.detail&&<small>{event.detail}</small>}</div></div>;})}</div>}

export default function Codex(){
  const [showIntro,setShowIntro]=useState(()=>localStorage.getItem('prism_codex_intro_seen')!=='1');
  const [mode,setMode]=useState('chat'); const [model,setModel]=useState('prism-mini-1.0');
  const [sessions,setSessions]=useState([]); const [sessionId,setSessionId]=useState(null); const [messages,setMessages]=useState([]); const [prompt,setPrompt]=useState('');
  const [loading,setLoading]=useState(false); const [phase,setPhase]=useState(''); const [steps,setSteps]=useState([]); const [elapsed,setElapsed]=useState(0); const [error,setError]=useState(''); const [plans,setPlans]=useState(false);
  const [files,setFiles]=useState(STARTER); const [projectId,setProjectId]=useState(null); const [projectName,setProjectName]=useState('Novo projeto'); const [activeFile,setActiveFile]=useState(STARTER[0].path); const [tab,setTab]=useState('preview'); const [search,setSearch]=useState(''); const [code,setCode]=useState(STARTER[0].content); const [nearBottom,setNearBottom]=useState(true);
  const chatRef=useRef(null); const startedAt=useRef(0); const abortRef=useRef(null); const fileTimers=useRef(new Set());
  const loadProject=useCallback(async()=>{const data=await api.get('/projects');let project=data.projects?.[0];if(!project){const created=await api.post('/projects',{name:'Novo projeto'});project=created.project;for(const file of STARTER)await api.post('/files',{projectId:project.id,path:file.path,content:file.content,kind:'file'});}const detail=await api.get(`/projects/${project.id}`);const loaded=detail.files?.length?detail.files.map(f=>({...f,kind:f.kind||'file'})):STARTER;const first=loaded.find(f=>f.kind!=='folder')||STARTER[0];setProjectId(project.id);setProjectName(project.name||'Novo projeto');setFiles(loaded);setActiveFile(first.path);setCode(first.content||'');},[]);
  const loadSessions=useCallback(async()=>{const data=await api.get('/chat/sessions');setSessions(data.sessions||[]);},[]);
  const openSession=useCallback(async(id)=>{setSessionId(id);setMode('chat');setError('');const data=await api.get(`/chat/sessions/${id}/messages`);setMessages((data.messages||[]).map(x=>({id:x.id,role:x.role,text:x.content,tokens:x.tokens_used})));},[]);
  const newChat=useCallback(async()=>{const data=await api.post('/chat/sessions',{title:'Nova conversa'});setSessions(x=>[data.session,...x]);setSessionId(data.session.id);setMessages([]);setMode('chat');setError('');requestAnimationFrame(()=>chatRef.current?.scrollTo({top:0}));},[]);
  useEffect(()=>{Promise.all([loadProject(),loadSessions()]).catch(e=>setError(e.message||'Não foi possível carregar o Codex.'));return()=>fileTimers.current.forEach(t=>clearInterval(t));},[loadProject,loadSessions]);
  useEffect(()=>{if(!sessionId&&sessions[0])openSession(sessions[0].id).catch(()=>{});},[sessionId,sessions,openSession]);
  useEffect(()=>{if(!loading)return undefined;const timer=setInterval(()=>setElapsed(Date.now()-startedAt.current),100);return()=>clearInterval(timer);},[loading]);
  const handleScroll=useCallback(()=>{const node=chatRef.current;if(node)setNearBottom(node.scrollHeight-node.scrollTop-node.clientHeight<96);},[]);
  useEffect(()=>{if(nearBottom)chatRef.current?.scrollTo({top:chatRef.current.scrollHeight,behavior:'smooth'});},[messages,loading,nearBottom]);
  const sendChat=useCallback(async(value)=>{let sid=sessionId;if(!sid){const created=await api.post('/chat/sessions',{title:value.slice(0,64)});sid=created.session.id;setSessionId(sid);setSessions(x=>[created.session,...x]);}setMessages(x=>[...x,{id:`user-${Date.now()}`,role:'user',text:value}]);setPrompt('');setLoading(true);setError('');try{const result=await api.post(`/chat/sessions/${sid}/messages`,{content:value,model,effort:'medium'},{timeout:90000});setMessages(x=>[...x,{id:result.message?.id||`assistant-${Date.now()}`,role:'assistant',text:result.message?.content||'',tokens:result.message?.tokens_used,providers:result.providers_used||[]}]);}catch(e){setError(e.message||'A resposta falhou.');}finally{setLoading(false);}},[model,sessionId]);
  const sendVibe=useCallback(async(value)=>{if(!projectId)return;setMessages(x=>[...x,{id:`user-${Date.now()}`,role:'user',text:value}]);setPrompt('');setLoading(true);setMode('vibe');setPhase('received');setSteps([]);setError('');startedAt.current=Date.now();setElapsed(0);const controller=new AbortController();abortRef.current=controller;try{const result=await api.streamPost('/ai/generate/stream',{model,thinking:'ultracode',prompt:value,context:messages.slice(-12).map(x=>`${x.role}: ${x.text}`).join('\n'),projectId},event=>{if(event.type==='phase'){setPhase(event.phase);setSteps(x=>[...x.filter(y=>y.phase!==event.phase),event]);}if(event.type==='artifact'){setTab('code');setActiveFile(event.path);const full=String(event.content||'');setFiles(x=>x.some(y=>y.path===event.path)?x.map(y=>y.path===event.path?{...y,content:full,kind:'file'}:y):[...x,{path:event.path,content:full,kind:'file'}]);let cursor=0;const timer=setInterval(()=>{cursor=Math.min(full.length,cursor+Math.max(24,Math.ceil(full.length/70)));setCode(full.slice(0,cursor));if(cursor>=full.length){clearInterval(timer);fileTimers.current.delete(timer);}},20);fileTimers.current.add(timer);}}, {timeout:180000,signal:controller.signal});await loadProject();setMessages(x=>[...x,{id:`assistant-${Date.now()}`,role:'assistant',text:result.text||'Alterações aplicadas ao projeto.',files:[...(result.files_created||[]),...(result.files_changed||[])],tools:(result.tools_used||[]).filter(x=>x?.tool)}]);}catch(e){if(e.name!=='AbortError')setError(e.message||'O agente não conseguiu concluir a tarefa.');}finally{setLoading(false);abortRef.current=null;}},[loadProject,messages,model,projectId]);
  const send=useCallback(()=>{const value=prompt.trim();if(!value||loading)return;if(mode==='vibe'||VIBE_PATTERN.test(value))sendVibe(value);else sendChat(value);},[loading,mode,prompt,sendChat,sendVibe]);
  const stop=()=>abortRef.current?.abort(); const selectFile=file=>{if(!file||file.kind==='folder')return;setActiveFile(file.path);setCode(file.content||'');setTab('code');};
  const visibleFiles=useMemo(()=>files.filter(f=>!search||f.path.toLowerCase().includes(search.toLowerCase())),[files,search]);
  const introDone=()=>{localStorage.setItem('prism_codex_intro_seen','1');setShowIntro(false);}; const replayIntro=()=>{localStorage.removeItem('prism_codex_intro_seen');setShowIntro(true);};
  return <div className="pcx-root">
    {showIntro&&<PrismCodexIntro onComplete={introDone}/>}<aside className="pcx-sidebar">
      <div className="pcx-brand"><span className="pcx-brand-mark">P</span><div><strong>Prism</strong><small>Codex</small></div></div>
      <button className="pcx-new" onClick={newChat}>+ <span>Novo chat</span></button>
      <nav className="pcx-nav"><button className={mode==='chat'?'active':''} onClick={()=>setMode('chat')}>Chat</button><button className={mode==='vibe'?'active':''} onClick={()=>setMode('vibe')}>Vibe Code <small>quando necessário</small></button><button onClick={()=>setPlans(true)}>Planos</button></nav>
      <div className="pcx-history"><div className="pcx-history-head"><span>Conversas</span><button onClick={newChat}>+</button></div><div className="pcx-history-list">{sessions.length===0&&<span className="pcx-muted">Nenhuma conversa ainda</span>}{sessions.map(s=><button key={s.id} className={sessionId===s.id?'selected':''} onClick={()=>openSession(s.id)}>{s.title||'Nova conversa'}</button>)}</div></div>
      <div className="pcx-sidebar-foot"><button onClick={replayIntro}>Apresentação do Codex</button><button onClick={()=>setPlans(true)}><span>Plano</span><strong>Grátis</strong></button></div>
    </aside>
    <main className="pcx-main"><header className="pcx-header"><div className="pcx-header-title"><span>PRISM CODEX</span><strong>{mode==='vibe'?'Vibe Code':'Chat'}</strong></div><div className="pcx-header-controls"><label>Modelo<select value={model} onChange={e=>setModel(e.target.value)}>{MODELS.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>{mode==='vibe'&&<button className="pcx-back" onClick={()=>setMode('chat')}>Voltar ao chat</button>}</div></header>
      <div className={`pcx-content ${mode==='vibe'?'with-workspace':''}`}><section className="pcx-chat-panel"><div className="pcx-chat-scroll" ref={chatRef} onScroll={handleScroll}>
        {messages.length===0&&<div className="pcx-welcome"><div className="pcx-welcome-mark">P</div><p>PRISM CODEX</p><h1>O que você quer fazer?</h1><span>Converse normalmente. Quando o pedido exigir construção, arquivos ou código, o Vibe Code assume o trabalho.</span></div>}
        {messages.map(m=><article key={m.id} className={`pcx-message ${m.role}`}><div className="pcx-message-label">{m.role==='user'?'Você':'Prism'}</div><div className="pcx-message-text">{m.text}</div>{m.files?.length>0&&<div className="pcx-message-files">{m.files.map(f=><button key={f} onClick={()=>selectFile(files.find(x=>x.path===f))}>{f}</button>)}</div>}{m.providers?.length>0&&<div className="pcx-message-meta">{m.providers.join(' · ')}</div>}{m.tools?.length>0&&<div className="pcx-message-meta">MCP · {m.tools.map(x=>x.tool).join(', ')}</div>}</article>)}
        {loading&&<article className="pcx-message assistant pcx-live-message"><div className="pcx-message-label">Prism {mode==='vibe'?'· agente':''}</div>{mode==='vibe'?<><div className="pcx-live-head"><strong>{PHASES.find(x=>x[0]===phase)?.[1]||'Trabalhando'}</strong><span>{(elapsed/1000).toFixed(1)}s</span></div><StepList phase={phase} steps={steps}/></>:<div className="pcx-typing"><i></i><i></i><i></i></div>}</article>}
        {error&&<div className="pcx-error"><strong>Não foi possível concluir</strong><span>{error}</span></div>}
      </div>{!nearBottom&&<button className="pcx-jump" onClick={()=>chatRef.current?.scrollTo({top:chatRef.current.scrollHeight,behavior:'smooth'})}>Ir para o fim</button>}
        <div className="pcx-composer-wrap"><div className="pcx-composer"><textarea value={prompt} rows={1} placeholder={mode==='vibe'?'Descreva o que você quer construir...':'Como posso ajudar você hoje?'} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}}}/><div className="pcx-composer-bar"><span>{mode==='vibe'?'Vibe Code · projeto real':'Chat · resposta rápida'}</span>{loading?<button className="pcx-stop" onClick={stop}>Parar</button>:<button className="pcx-send" onClick={send} disabled={!prompt.trim()}>Enviar</button>}</div></div><small className="pcx-composer-note">Enter envia · Shift + Enter quebra a linha</small></div>
      </section>
      {mode==='vibe'&&<section className="pcx-workspace"><div className="pcx-workspace-top"><div><span>WORKSPACE</span><strong>{projectName}</strong></div><nav><button className={tab==='preview'?'active':''} onClick={()=>setTab('preview')}>Preview</button><button className={tab==='code'?'active':''} onClick={()=>setTab('code')}>Código</button></nav></div>{tab==='preview'?<iframe className="pcx-preview" title="Preview real do projeto" sandbox="allow-scripts" srcDoc={previewFor(files)||'<html><body style="margin:0;display:grid;place-items:center;height:100vh;font-family:system-ui;color:#555">Aguardando arquivos do agente.</body></html>'}/>:<div className="pcx-editor"><aside className="pcx-tree"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar arquivos"/>{visibleFiles.map(f=><button key={f.path} className={f.path===activeFile?'active':''} onClick={()=>selectFile(f)}><span>{f.kind==='folder'?'▾':'·'}</span>{f.path}</button>)}</aside><div className="pcx-code"><div className="pcx-code-head"><span>{activeFile}</span><small>{language(activeFile)}</small></div><pre>{code.split('\n').map((line,i)=><div key={i}><span>{i+1}</span><code>{line||' '}</code></div>)}</pre></div></div>}</section>}
      </div>
    </main>
    {plans&&<div className="pcx-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setPlans(false)}}><section className="pcx-plans"><header><div><span>PRISM</span><h2>Planos</h2></div><button onClick={()=>setPlans(false)}>Fechar</button></header><div className="pcx-plan-grid">{PLAN_DATA.map(([name,price,models,limits])=><article key={name} className={name==='Grátis'?'current':''}><div><strong>{name}</strong><span>{price}</span></div><p>{models}</p><small>{limits}</small>{name!=='Grátis'&&<button>Fazer Upgrade</button>}</article>)}</div><footer>Stripe preparado para ativação futura. Cobrança real desativada.</footer></section></div>}
  </div>;
}
