import { Link, useParams } from 'react-router-dom';
import { useAuth } from '../lib/auth.jsx';

const TOPICS={
roteamento:['Roteamento','Como a Prism decide quais motores participam de uma tarefa.',['O perfil Prism transforma a solicitação em uma estratégia de execução. Perfis leves podem chamar um ou dois motores; Taff e Ultracode podem distribuir a mesma tarefa em paralelo.','Depois das chamadas, uma etapa de síntese compara as respostas disponíveis e produz um resultado único. Se um provedor falhar, o backend deve tratar a falha sem expor credenciais.']],
motores:['Motores externos','A Prism é uma camada de orquestração sobre serviços externos.',['Gemini é usado para planejamento, raciocínio conceitual e contexto. Groq é usado quando velocidade de inferência é importante para geração e refatoração.','NVIDIA NIM pode ser acessado via OpenRouter para validação, otimização e revisão. A disponibilidade depende dos provedores.']],
openrouter:['OpenRouter','Uma camada intermediária para acessar modelos diferentes por uma API unificada.',['A Prism mantém a credencial do OpenRouter exclusivamente no backend. O navegador nunca recebe essa chave.','O resultado também depende do modelo, disponibilidade, limites e comportamento do serviço intermediário.']],
orquestracao:['Orquestração paralela','Vários motores podem trabalhar sobre a mesma solicitação antes da resposta final.',['Chamadas independentes podem ser executadas em paralelo para reduzir o tempo total.','A síntese compara as respostas e tenta produzir uma saída coerente. Ultracode prioriza profundidade e validação em troca de maior latência e consumo.']],
creditos:['Créditos e tokens','Como esforço computacional se transforma em consumo.',['Tokens são unidades usadas pelos motores para processar texto; contexto maior normalmente aumenta o consumo.','Créditos representam a cota da Prism e podem considerar tokens, quantidade de motores e nível de esforço.']],
privacidade:['Privacidade e isolamento','Cada conta possui seu próprio espaço no banco.',['Sessões e mensagens são vinculadas ao usuário autenticado e consultas devem validar essa propriedade.','DATABASE_URL, JWT_SECRET e chaves dos provedores ficam somente no servidor. O histórico é filtrado pelo usuário.']],
limites:['Limites e rate limiting','Proteções para manter a API estável.',['A API limita requisições para reduzir abuso e picos.','Planos podem controlar créditos, modelos e esforço; essa autorização deve ser aplicada no backend. Falhas retornam códigos HTTP úteis sem revelar segredos.']]
};
function Header(){const {user}=useAuth();const label=user?.name||user?.email?.split('@')[0]||'Perfil';return <header className="site-header"><Link to="/" className="site-brand"><span className="site-mark"/>PRISM IA</Link><nav><Link to="/informacoes">Informações</Link><Link to="/modelos">Modelos</Link><Link className="active" to="/termos">Termos</Link></nav>{user?<Link to="/chat" className="site-account"><span>{label.slice(0,2).toUpperCase()}</span>{label}</Link>:<Link to="/login" className="site-login">Login</Link>}</header>}
export default function TermDetail(){const {topic}=useParams();const data=TOPICS[topic]||TOPICS.roteamento;return <div className="editorial-page term-detail"><Header/><main><section className="detail-head"><Link to="/termos" className="detail-back">← Todos os termos</Link><div className="eyebrow">PRISM / TERMOS</div><h1>{data[0]}</h1><p className="lead">{data[1]}</p></section><section className="detail-body">{data[2].map((text,i)=><article key={i}><span>{String(i+1).padStart(2,'0')}</span><div><h2>{i===0?'Visão geral':'Na prática'}</h2><p>{text}</p></div></article>)}</section><section className="detail-nav"><Link to="/termos">Ver todos os termos</Link><Link to="/">Página inicial</Link></section></main></div>}
export {TOPICS};
